<h2 style="color:purple" align="center">Working With Numpy</h2>

In [15]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
c = np.concatenate((a,b),axis = 0)
d= np.vstack((a,b))
print(c)
print(d)
e = np.concatenate((a,b),axis = 1)
f= np.hstack((a,b))
print(e)
print(f)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [17]:
a =np.arange(300).reshape(3,10,10)
c = a.sum(axis = 0) #Column
print(a)
# array --> 3 dimen --> sum --> 2 dimen

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 223 224 225 2

In [18]:
print(c)

[[300 303 306 309 312 315 318 321 324 327]
 [330 333 336 339 342 345 348 351 354 357]
 [360 363 366 369 372 375 378 381 384 387]
 [390 393 396 399 402 405 408 411 414 417]
 [420 423 426 429 432 435 438 441 444 447]
 [450 453 456 459 462 465 468 471 474 477]
 [480 483 486 489 492 495 498 501 504 507]
 [510 513 516 519 522 525 528 531 534 537]
 [540 543 546 549 552 555 558 561 564 567]
 [570 573 576 579 582 585 588 591 594 597]]


In [25]:
import pandas as pd
d = {"one": (1,2,3,4), "two": (5,6,7,8)}
df = pd.DataFrame(data = d,index =[1,2,3,4])
df

one  two
1    1    5
2    2    6
3    3    7
4    4    8